# ? ??? github action?? github secret? ?????, AWS Secret manager? ?? key? ????????.

blog:
  search:
    kakao:
      apiKey: "3fe1d1cf3d8a9924be09220c78cd6280"
    naver:
      clientId: "0OneZosq6U7J2lPRbv5q"
      clientSecret: "iRW6lbWFzq"

spring:
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
